name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: localaifinance-e8h8afgyd0b8gtd2    # Set this to your Azure Web App name
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install backend dependencies
      run: npm ci

    - name: Install frontend dependencies
      run: cd client && npm ci

    - name: Build React frontend
      run: cd client && npm run build

    - name: Create deployment package
      run: |
        mkdir -p deploy
        cp -r node_modules deploy/
        cp -r client/build deploy/client/
        cp server.js deploy/
        cp package.json deploy/
        cp web.config deploy/
        cp .env.example deploy/.env

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./deploy
